<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Drawing" Version="26.7.0">
      <Aliases>AsposeDrawing</Aliases>
    </PackageReference>
    <PackageReference Include="Azure.AI.FormRecognizer" Version="4.1.0" />
    <PackageReference Include="Aspose.PDF" Version="24.9.0" />
    <PackageReference Include="Aspose.Words" Version="24.9.0" />
    <PackageReference Include="Aspose.Cells" Version="24.9.0" />
    <PackageReference Include="Aspose.Slides.NET" Version="24.9.0" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.43.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
